language: python
arch:
  - amd64
  - ppc64le
python:
  - "2.7_with_system_site_packages"
  - "3.7"
  - "3.8"
  
# command to install dependencies, e.g.
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls
# command to run tests, e.g. python setup.py test
env: PYGAC_CONFIG_FILE=etc/pygac.cfg.template

jobs:
  exclude:
   - arch : ppc64le
     python :  
       - "2.7_with_system_site_packages"
       - "3.7"
       - "3.9"
script: coverage run --source=pygac setup.py test
before_install:
- if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then 
      echo "here ppc";
      sudo apt-get install lapack ;
      sudo apt-get install  libstdc++ ;
      sudo apt-get install  .builddeps
      sudo apt-get install gcc
      sudo apt-get install g++ 
      sudo apt-get install gfortran musl-dev lapack-dev ;
      pip install scipy ;
      sudo apt-getinstall del .builddeps;
      sudo rm -rf /root/.cache;
      pip uninstall h5py;
      pip install --no-cache-dir h5py;
  else    
      sudo apt-get install -qq python-numpy python-h5py python-scipy libhdf5-serial-dev;
      echo "here else ppc";
  fi
after_success: coveralls
deploy:
  provider: pypi
  user: adybbroe
  password:
    secure: FznD38SHxuj1RoFXUqLstF//O3+pypF84hCOHO8A3Poa+ygh7X4a+9aimCeiuY9d+5tbE0ZlyG7LMcCOFA3JCvH7lUChmQbbn3pcFvJdJzzYQgxYNfvCL9YtjRF/n648bVdpN265hm07rmOe7DHbysw4q8hMlxtUH87MYctRg90=
  on:
    tags: true
    repo: pytroll/pygac
    branch: master
