language: python
arch:
  - amd64
  - ppc64le
python:
  - "2.7_with_system_site_packages"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies, e.g.
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls
# command to run tests, e.g. python setup.py test
env: PYGAC_CONFIG_FILE=etc/pygac.cfg.template

jobs:
  exclude:
   - arch : ppc64le
     python :  
       - "2.7_with_system_site_packages"
script: coverage run --source=pygac setup.py test
before_install:
- if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then 
      sudo apt-get update ;
      sudo apt-get install --upgrade --no-cache \
              bash openssh curl ca-certificates openssl less htop \
              g++ make wget rsync \
              build-base libpng-dev freetype-dev libexecinfo-dev openblas-dev libgomp lapack-dev \
              libgcc libquadmath musl  \
              libgfortran \
              lapack-dev ;
      sudo  pip install --no-cache-dir --upgrade pip ;
      sudo  pip install numpy==1.17.3 ;
      sudo  pip install scipy==1.3.1 ;
  else    
      sudo apt-get install -qq python-numpy python-h5py python-scipy libhdf5-serial-dev;
  fi
after_success: coveralls
deploy:
  provider: pypi
  user: adybbroe
  password:
    secure: FznD38SHxuj1RoFXUqLstF//O3+pypF84hCOHO8A3Poa+ygh7X4a+9aimCeiuY9d+5tbE0ZlyG7LMcCOFA3JCvH7lUChmQbbn3pcFvJdJzzYQgxYNfvCL9YtjRF/n648bVdpN265hm07rmOe7DHbysw4q8hMlxtUH87MYctRg90=
  on:
    tags: true
    repo: pytroll/pygac
    branch: master
